//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectGSL.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserProject
    {
        public int userId { get; set; }
        public int projectId { get; set; }
        public bool isActive { get; set; }
        public System.DateTime assignedDate { get; set; }
    
        public virtual tb_Project tb_Project { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
